name: Entregable8 Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish .NET Core Project
      run: dotnet publish Entregable8.csproj -c Release -o release --nologo

    - name: Publish en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        publish_dir: ./publish/wwwroot
