name: Entregable8 Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish .NET Core Project
      run: dotnet publish Entregable8.csproj -c Release -o release --nologo

    - name: Change base-tag in index.html from / to Entregable8
      run: sed -i 's/<base href="\/" \/>/<base href="\/Entregable8\/" \/>/g' release/wwwroot/index.html
      
    - name: cp index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Publish en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        publish_dir: ./publish/wwwroot
